name: GitHub Action To Create Clickup Card for Depandabot PR's
run-name: GitHub Action To Create Clickup Card for Depandabot PR's 🚀
on: 
  pull_request:
    types: opened
    branches: [ $default-branch ]
    
jobs:
  Create-Clickup-Card:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }} # This step only runs when PR has dependabot/ HEAD
    runs-on: ubuntu-latest
    steps:
      - name: Depandabot - Clickup Integration 
        run: echo "🎉 The job was triggered by a ${{ github.actor }}." 

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.PAT }}"

                
      - name: Test custom action - clickup integration - ${{ github.actor }}
        id: clickup-task-creation
        uses: ritik-deriv/clickup-action@v1.9.29
        with:
          clickup_api_token: "${{ secrets.CLICKUP_API_TOKEN }}"
          github_token: "${{ secrets.PAT }}"
          pull_request_title: "[${{ github.repository }}] - ${{ github.event.pull_request.title }}"
          vulnerable_version: "${{ steps.dependabot-metadata.outputs.previous-version }}"
          fixed_version: "${{ steps.dependabot-metadata.outputs.new-version }}"
          dependency_type: "${{ steps.dependabot-metadata.outputs.dependency-type }}"
          vulnerable_package: "${{ steps.dependabot-metadata.outputs.dependency-names }}"
          pull_request_number: "${{ github.event.number }}"
          github_repository: "${{ github.repository }}"
